#!/bin/bash
# Setup WalterSignal iTerm2 Profile
# This script configures iTerm2 for optimal WalterSignal development

set -e

echo "🚀 Setting up WalterSignal iTerm2 Profile..."
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

# Check if iTerm2 is running
if ! pgrep -x "iTerm2" > /dev/null; then
    echo "⚠️  iTerm2 is not running. Please start iTerm2 and run this script again."
    exit 1
fi

echo -e "${BLUE}Step 1: Profile Configuration${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "I've created a dynamic profile at:"
echo "  ~/.config/iterm2/waltersignal-profile.json"
echo ""
echo "This profile includes:"
echo "  ✓ Purple accent colors (WalterSignal brand)"
echo "  ✓ 'WS' badge in corner"
echo "  ✓ Working directory: ~/.claude/command-center/erp-dashboard"
echo "  ✓ Automatic error/success highlighting"
echo "  ✓ Build completion alerts"
echo ""

echo -e "${BLUE}Step 2: Import Profile (Manual)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To import the profile into iTerm2:"
echo ""
echo "  1. Open iTerm2 Preferences (Cmd+,)"
echo "  2. Go to: Profiles → Other Actions (bottom left)"
echo "  3. Click: 'Import JSON Profiles...'"
echo "  4. Select: ~/.config/iterm2/waltersignal-profile.json"
echo "  5. Click: 'Import'"
echo ""
echo "Press ENTER when you've imported the profile..."
read -r

echo ""
echo -e "${BLUE}Step 3: Configure Triggers${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "The profile includes these triggers:"
echo ""
echo -e "  ${GREEN}✓ Success Highlighting${NC}"
echo "     Pattern: '✓ Compiled|Success|BUILD SUCCESS'"
echo "     Action: Green background highlight"
echo ""
echo -e "  ${PURPLE}✗ Error Highlighting${NC}"
echo "     Pattern: 'Error|Failed|error'"
echo "     Action: Red background highlight"
echo ""
echo -e "  ${BLUE}⚠ Warning Highlighting${NC}"
echo "     Pattern: 'Warning|warning|WARN'"
echo "     Action: Yellow background highlight"
echo ""
echo -e "  ${PURPLE}🔔 Build Alert${NC}"
echo "     Pattern: '✓ Ready in'"
echo "     Action: macOS notification"
echo ""

echo -e "${BLUE}Step 4: Keyboard Shortcuts${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Essential shortcuts for split pane workflow:"
echo ""
echo "  Cmd+D          Split vertically (Claude | Logs)"
echo "  Cmd+Shift+D    Split horizontally"
echo "  Cmd+[          Switch to left pane"
echo "  Cmd+]          Switch to right pane"
echo "  Cmd+Opt+Arrow  Jump to pane in direction"
echo "  Cmd+W          Close current pane"
echo ""
echo "  Cmd+Shift+M    Add mark (before long commands)"
echo "  Cmd+Shift+Up   Jump to previous mark"
echo "  Cmd+Shift+A    Select command output"
echo ""
echo "  Cmd+Opt+A      Alert on next command completion"
echo "  Cmd+Opt+B      Toggle toolbelt (captured output)"
echo ""

echo -e "${BLUE}Step 5: Quick Access Shortcut${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To open WalterSignal profile quickly:"
echo ""
echo "  1. In iTerm2 Preferences → Profiles"
echo "  2. Select 'WalterSignal Development' profile"
echo "  3. Click 'Set as Default' (optional)"
echo ""
echo "Or assign a keyboard shortcut:"
echo ""
echo "  1. Preferences → Keys → Key Bindings"
echo "  2. Click '+' to add new binding"
echo "  3. Press: Cmd+Opt+W"
echo "  4. Action: 'Select Menu Item...'"
echo "  5. Enter: 'Profiles → WalterSignal Development'"
echo ""

echo -e "${BLUE}Step 6: Test the Setup${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Let's verify everything works:"
echo ""
echo "  1. Open new window with WalterSignal profile (Cmd+N)"
echo "  2. Split pane vertically (Cmd+D)"
echo "  3. In right pane, run:"
echo "     cd ~/.claude/command-center/erp-dashboard"
echo "     npm run dev"
echo "  4. Watch for green '✓ Compiled' highlights"
echo "  5. You should see purple 'WS' badge in corner"
echo ""

echo -e "${GREEN}✓ Setup Complete!${NC}"
echo ""
echo "Your WalterSignal development environment is ready."
echo ""
echo "Recommended layout for development:"
echo ""
echo "  ┌─────────────────────┬─────────────────────┐"
echo "  │                     │                     │"
echo "  │   Claude Code       │   Dev Server Logs   │"
echo "  │   (left pane)       │   (right pane)      │"
echo "  │                     │                     │"
echo "  │   Work here         │   Watch for errors  │"
echo "  │   with AI           │   and builds        │"
echo "  │                     │                     │"
echo "  └─────────────────────┴─────────────────────┘"
echo ""
echo "Press ENTER to finish..."
read -r

echo ""
echo "🎉 All done! Happy coding with WalterSignal!"
