#!/bin/bash
# Automated Project Research using Perplexity Pro
# Author: Claude Code
# Usage: ./research-project.sh [project-name] "[research-query]"

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Paths
CLAUDE_DIR="$HOME/.claude"
PROJECTS_DIR="$CLAUDE_DIR/projects"

# Function to perform research
perform_research() {
    local project_name="$1"
    local research_query="$2"
    local project_path="$PROJECTS_DIR/$project_name"

    if [ ! -d "$project_path" ]; then
        echo -e "${RED}❌ Project not found: $project_name${NC}"
        exit 1
    fi

    # Create research directory if it doesn't exist
    local research_dir="$project_path/research"
    mkdir -p "$research_dir"

    echo -e "${BLUE}🔍 Automated Research for: $project_name${NC}\n"
    echo -e "${GREEN}📝 Query: $research_query${NC}\n"
    echo -e "${BLUE}⏳ Searching with Perplexity Pro...${NC}\n"

    # Generate filename based on query and date
    local filename=$(echo "$research_query" | tr '[:upper:]' '[:lower:]' | tr -s ' ' '-' | tr -cd '[:alnum:]-' | cut -c1-50)
    local timestamp=$(date '+%Y-%m-%d')
    local output_file="$research_dir/${timestamp}-${filename}.md"

    # Create research prompt for Claude Code
    local research_prompt="Use Perplexity to research: \"$research_query\"

Focus on:
- Official documentation and resources
- Community resources (GitHub, forums, discussions)
- Best practices and implementation guides
- Recent developments and updates (last 6 months)
- Common issues and solutions

Please format the results as a comprehensive markdown document with:
1. Summary
2. Key Findings
3. Resources (with links)
4. Implementation Notes
5. Next Steps

Save the results to: $output_file"

    echo -e "${GREEN}📄 Research will be saved to:${NC}"
    echo -e "   $output_file\n"

    echo -e "${BLUE}💡 How to complete this research:${NC}"
    echo -e "   1. Open Claude Code in the project directory:"
    echo -e "      ${YELLOW}cd $project_path && claude${NC}"
    echo -e "   2. Paste this prompt:"
    echo -e "${YELLOW}────────────────────────────────────────${NC}"
    echo -e "$research_prompt"
    echo -e "${YELLOW}────────────────────────────────────────${NC}\n"

    echo -e "${BLUE}📋 Copying prompt to clipboard...${NC}"
    echo "$research_prompt" | pbcopy
    echo -e "${GREEN}✅ Prompt copied! Paste it in Claude Code.${NC}\n"

    # Create a placeholder file
    cat > "$output_file" << EOF
# Research: $research_query

**Date**: $timestamp
**Project**: $project_name
**Status**: In Progress

## Query
$research_query

## Notes
Research in progress using Perplexity Pro...

---
*Generated by Claude Code Project Manager*
EOF

    echo -e "${GREEN}✅ Research session initialized!${NC}\n"
    echo -e "${BLUE}📂 Research directory: $research_dir${NC}"
}

# Function to list recent research
list_research() {
    local project_name="$1"
    local project_path="$PROJECTS_DIR/$project_name"
    local research_dir="$project_path/research"

    if [ ! -d "$research_dir" ]; then
        echo -e "${YELLOW}⚠️  No research directory found for: $project_name${NC}"
        return
    fi

    echo -e "${BLUE}📚 Recent Research for: $project_name${NC}\n"

    local count=0
    for file in "$research_dir"/*.md; do
        if [ -f "$file" ]; then
            local filename=$(basename "$file")
            local filedate=$(echo "$filename" | cut -d'-' -f1-3)
            echo -e "${GREEN}  • $filedate${NC} - $(basename "$file" .md | cut -d'-' -f4-)"
            ((count++))
        fi
    done

    if [ $count -eq 0 ]; then
        echo -e "${YELLOW}  No research files found${NC}"
    fi
    echo ""
}

# Main script
echo -e "${BLUE}════════════════════════════════════════${NC}"
echo -e "${BLUE}    Perplexity Pro Research Automation${NC}"
echo -e "${BLUE}════════════════════════════════════════${NC}\n"

if [ $# -eq 0 ]; then
    echo -e "${YELLOW}Usage:${NC}"
    echo -e "  Research: ${GREEN}$0 [project-name] \"[research-query]\"${NC}"
    echo -e "  List:     ${GREEN}$0 [project-name] --list${NC}\n"
    echo -e "${YELLOW}Examples:${NC}"
    echo -e "  $0 granola \"Granola meeting notes automation tools\""
    echo -e "  $0 lifehub-2.0 \"React dashboard UI best practices\""
    echo -e "  $0 granola --list\n"
    exit 1
fi

project_name="$1"

if [ $# -eq 1 ] || [ "$2" = "--list" ]; then
    list_research "$project_name"
else
    research_query="$2"
    perform_research "$project_name" "$research_query"
fi
