#!/bin/bash
# ============================================================
# Cron Job Setup for Cost Tracking Automations
# Installs weekly schedule for all cost trackers
#
# Usage: ./setup-cron-jobs.sh
# Schedule: Run once to install, automations run weekly
# ============================================================

SCRIPT_DIR="/Users/mikefinneran/Documents/ObsidianVault/.scripts"
CRON_FILE="/tmp/stanny-cron-jobs.txt"

echo "🤖 SpecialAgentStanny - Cron Job Setup"
echo "============================================================"
echo ""

# Check if scripts exist
echo "Step 1: Verifying automation scripts..."
SCRIPTS=(
    "run-all-trackers.sh"
    "fetch-subscription-invoices.py"
    "github-actions-tracker.py"
    "anthropic-api-tracker.py"
    "perplexity-api-tracker.py"
)

MISSING=0
for script in "${SCRIPTS[@]}"; do
    if [ -f "$SCRIPT_DIR/$script" ]; then
        echo "   ✅ $script"
    else
        echo "   ❌ $script NOT FOUND"
        MISSING=1
    fi
done

if [ $MISSING -eq 1 ]; then
    echo ""
    echo "❌ Some scripts are missing!"
    echo "Run the build process first, then try again."
    exit 1
fi

echo ""
echo "Step 2: Checking current cron jobs..."

# Get existing cron jobs (if any)
crontab -l > "$CRON_FILE" 2>/dev/null || touch "$CRON_FILE"

# Check if automation already scheduled
if grep -q "run-all-trackers.sh" "$CRON_FILE"; then
    echo "⚠️  Automation already scheduled in cron!"
    echo ""
    echo "Current schedule:"
    grep "run-all-trackers.sh" "$CRON_FILE"
    echo ""
    read -p "Replace existing schedule? (y/N): " REPLACE

    if [ "$REPLACE" != "y" ] && [ "$REPLACE" != "Y" ]; then
        echo "✅ Keeping existing schedule"
        rm "$CRON_FILE"
        exit 0
    fi

    # Remove old schedule
    grep -v "run-all-trackers.sh" "$CRON_FILE" > "$CRON_FILE.tmp"
    mv "$CRON_FILE.tmp" "$CRON_FILE"
    echo "✅ Removed old schedule"
fi

echo ""
echo "Step 3: Installing cron jobs..."

# Add header comment
cat >> "$CRON_FILE" << 'EOF'

# ============================================================
# SpecialAgentStanny Cost Tracking Automations
# Runs weekly to track subscription and API costs
# Generated by setup-cron-jobs.sh
# ============================================================

EOF

# Add weekly automation (Sundays at 9 AM)
echo "0 9 * * 0 $SCRIPT_DIR/run-all-trackers.sh >> $SCRIPT_DIR/logs/cron_run.log 2>&1" >> "$CRON_FILE"

# Install cron jobs
crontab "$CRON_FILE"

if [ $? -eq 0 ]; then
    echo "✅ Cron jobs installed successfully!"
else
    echo "❌ Failed to install cron jobs"
    rm "$CRON_FILE"
    exit 1
fi

# Clean up temp file
rm "$CRON_FILE"

echo ""
echo "Step 4: Verifying installation..."
echo ""
echo "Current cron schedule:"
echo "-----------------------------------------------------------"
crontab -l | grep -A 5 "SpecialAgentStanny"
echo "-----------------------------------------------------------"
echo ""

echo "📅 Schedule Details:"
echo "   ⏰ Every Sunday at 9:00 AM"
echo "   📊 Runs all 4 cost trackers:"
echo "      1. Gmail subscription invoices"
echo "      2. GitHub Actions usage"
echo "      3. Anthropic API usage analysis"
echo "      4. Perplexity Pro vs API analysis"
echo ""
echo "   📁 Reports saved to: $SCRIPT_DIR/../"
echo "   📝 Logs saved to: $SCRIPT_DIR/logs/"
echo ""

echo "============================================================"
echo "🎉 Cron Setup Complete!"
echo "============================================================"
echo ""
echo "📋 Next Steps:"
echo "1. ✅ Automations will run weekly automatically"
echo "2. 📊 Check reports in Obsidian Vault root"
echo "3. 📝 Monitor logs in .scripts/logs/"
echo ""
echo "💡 Manual Run:"
echo "   cd $SCRIPT_DIR"
echo "   ./run-all-trackers.sh"
echo ""
echo "🔧 Modify Schedule:"
echo "   crontab -e"
echo ""
echo "❌ Remove Schedule:"
echo "   crontab -e (delete the SpecialAgentStanny section)"
echo ""
echo "⚠️  IMPORTANT: First run requires OAuth setup!"
echo "   Run once manually to authorize Gmail:"
echo "   python3 $SCRIPT_DIR/gmail-oauth-setup.py"
echo ""
